Ansible 2
Otus-DevOps-2018-05/VladimirDe_infra pull request #10
Opened 2018-07-29 11:47 UTC by VladimirDe

# Выполнено ДЗ №9
  

- [ ] Основное ДЗ: создание плейбуков ansible для конфигурирования и деплоя reddit приложения; использование плейбуков ansible в packer
- [ ]   Задание со *: Исследование возможности использования dynamic inventory в GCP

## В процессе сделано:

- Созданы плейбуки ansible для конфигурирования и деплоя reddit приложения (site.yml, db.yml, app.yml, deploy.yml)
- Созданы плейбуки ansible (packer_db.yml, packer_app.yml), эти плейбуки использованы для провижинга в packer (app.json, db.json)
- Исследованы возможности использования dynamic inventory в GCP через contrib модуль ansible (gce.py) и terraform state file
- Настроен dynamic inventory (выбран и используется gce.py). Дополнительно написаны ansible плейбуки для конфигурирования dynamic inventory (terraform_dynamic_inventory_setup.yml, gce_dynamic_inventory_setup.yml). Плейбуки (app.yml, db.yml, deploy.yml) адаптированы с учетом dynamic inventory через gce.py
- Добавлена секция Homework-9 в README.md

## Как запустить проект:
Описано в 9.2 Как запустить проект в README.md
## Как проверить работоспособность:
Описано в 9.3 Как проверить проект в README.md
## PR checklist
- [ ]  Выставил label с темой домашнего задания (Ansible, ansible-2)

2018-07-29 11:48 UTC, VladimirDe commented
Сделана Ansible-2

2018-08-17 13:06 UTC, virtualshuric requested changes
Владимир, привет! Вроде все верно кроме одного - почему, в итоге, Ansible использует статический inventory? Как поправишь, будет аппрув и звездочка )

2018-08-17 18:08 UTC, VladimirDe commented
Привет. Достаточно запустить плейбук gce_dynamic_inventory_setup.yml

2018-09-17 08:41 UTC, virtualshuric approved these changes

2018-09-17 08:41 UTC, virtualshuric commented
по условиям ДЗ - надо было настроить динамику сразу. YML - посмотрел, он ОК. Так что можно мерджить

2018-09-27 06:06 UTC, merged