Adding template.md, integration with Travis CI and test.py
Otus-DevOps-2018-05/VladimirDe_infra pull request #2
Opened 2018-06-24 18:55 UTC by VladimirDe

Added corrected test.py (Travis CI successfully passed build)
![builds - otus-devops-2018-05vladimirde_infra - travis ci - google chrome](https://user-images.githubusercontent.com/40039450/41822502-3dabb556-77f9-11e8-8ff5-f5088cf0a440.jpg)

2018-06-25 16:19 UTC, serjs requested changes
Привет!

- Шаблон есть
- Исправления в CI вижу и статус ок

Принять PR не могу, т.к. у тебя в Github профиле не указаны Имя Фамилия, я и другие преподаватели не смогут тебя найти. Обнови пожалуйста, после я найду канал и тебя в ведомости и закроем PR

2018-06-25 18:46 UTC, VladimirDe commented
Меня зовут Владимир Денисов, имя в профиле Github обновил

2018-06-26 10:35 UTC, serjs approved these changes

2018-06-26 10:35 UTC, serjs commented
Отлично, нашел канал и отметил в ведомости, можно закрывать PR! 👍

2018-06-28 03:29 UTC, merged