Cloud bastion
Otus-DevOps-2018-05/VladimirDe_infra pull request #3
Opened 2018-06-30 03:41 UTC by VladimirDe

# Выполнено ДЗ №3

 - Основное ДЗ
 - Задание со *

## В процессе сделано:
 - созданы 2 инстанса в GCP
 - развёрнут VPN-сервер Pritunl

## В ветке cloud-bastion
 - скрипт установки Pritunl
 - файл установок Otus-DevOps-2018-05_test_bastion.ovpn для клиента OpenVPN
- 

## Как проверить работоспособность:
 - используя файл Otus-DevOps-2018-05_test_bastion.ovpn и клиент OpenVPN подсоединится к VPN серверу
- проверить доступность внутренного хоста (ключ не даю, поэтому наверное только ping 10.132.0.2) 

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-07-02 18:27 UTC, Nklya requested changes
Добрый вечер.

Владимир, проверки тревиса не проходят потому что у конфига VPN неверное имя файла и у скрипта setupvpn.sh и у README.md должны быть пустые строки в конце файла.

Это нужно пофиксить чтобы проверки стали зеленые

2018-07-02 18:27 UTC, Nklya commented on play-travis/test.py
> +
И зачем в этом ДЗ правится файл из прошлого?

2018-07-02 18:27 UTC, Nklya commented on Otus-DevOps-2018-05_test_bastion.ovpn
> +#{
Файл должен называться cloud-bastion.ovpn

2018-07-02 18:27 UTC, Nklya commented on setupvpn.sh
> +#!/bin/bash
У скрипта setupvpn.sh и у README.md должны быть пустые строки в конце файла.

2018-07-02 18:27 UTC, Nklya commented on README.md
> +
У скрипта setupvpn.sh и у README.md должны быть пустые строки в конце файла.

2018-07-02 18:28 UTC, Nklya commented
Ну и заодно нужно настроить гит корректно.
Сейчас там указан кривой e-mail, поэтому коммиты серые

<img width="293" alt="image" src="https://user-images.githubusercontent.com/26086394/42180159-d50203c4-7e3e-11e8-999f-55f88cc5a694.png">

2018-07-02 19:32 UTC, VladimirDe commented
К сожалению, всё равно не проходит проверки.

2018-07-02 19:36 UTC, Nklya commented
1. гит настрой нормально пожалуйста, еще раз говорю. последние три коммита кривые
![image](https://user-images.githubusercontent.com/26086394/42182828-38502e7a-7e48-11e8-8ec5-2a6f3ef10adc.png)

2. Теперь проверки не проходят потому что впн не поднимается.
Скорее всего по причине IPV6, там в чате в слаке писали про это недавно

2018-07-03 07:40 UTC, Nklya commented
Чтобы перезапустить билд, достаточно нажать кнопку re-run на вкладке Checks. 
Не нужно для этого коммитить

2018-07-03 15:46 UTC, Nklya commented
Ок, тесты падают из-за того что тревис не может подключится к твоему впн.
Я вручную импортировал конфиг и у меня подключился и пинг проходит, хоть и ругается при импорте.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/26086394/42230330-61a6c898-7ef1-11e8-894c-e3990e350363.png">

2018-07-03 15:47 UTC, Nklya approved these changes
Добрый вечер.

Владимир, условия ДЗ выполнены, все выглядит ок 👍 

VPN только пришлось руками проверять(

2018-07-03 15:48 UTC, Nklya commented on README.md
> +alias someinternalhost='-At -i appuser appuser@35.197.233.194 ssh appuser@10.132.0.2'
Тут бы еще стоило упомянуть про ~/.ssh/config
https://wiki.gentoo.org/wiki/SSH_jump_host#Setup

2018-07-04 05:31 UTC, merged

2018-07-04 09:36 UTC, Nklya commented
Опять кривые коммиты.

У тебя в одном месте настроен нормальный e-mail (который на gmail)
А на другом - яндексовый, поэтому коммиты идут серые.
Проверь ~/.gitconfig
<img width="387" alt="image" src="https://user-images.githubusercontent.com/26086394/42269392-b5835a04-7f86-11e8-8aec-ca7e4771b199.png">